import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Loading from "./components/loading";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: [ "400","500", "700",],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portofolio | Imam Muttaqin",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${inter.variable} antialiased overflow-x-hidden`}
      >
        <Navbar />

        <main>{children}</main>
        
        <Footer />
      </body>
    </html>
  );
}
